#.travis.yml

language: node_js
node_js:
  - "6.11.5"

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g typescript@2.7.2
  - cd functions
  - npm install

script:
  - npm run lint
  - npm run build

before_deploy:
  - cd ../

deploy:
  provider: firebase
  token:
    secure: foe1Q+v5zjG6vRJi+OpHEK54SMKpA9wkL4IdcBwEcT5SE6QJPA6+L4jSpQsQ2f2YwHNTAzqH7mi/vWVsHkXOnz7WVBvHl6MZLxnLi4hoCkv5MBzRTQhPeIvW1r9PfhXqVvDxeUi9wpS6LgV9KijBVP8a419HF7L3Hz2OkIC/HIKSQK8iUO5yZUyzUHzG5LqoTQWTK0Y93yDI/mR2GQgaKNRysxOh63CMuG1rsVGF1nRhxEDeGgCdJ2F/8Xx7qBczwAwhPm56XPuTjCmdH2GseBt5FcOR9tJ1i2qu0tYdXWmBeLykcV1fXXScb+lhESIQElNXUWHxPmGus2tnTsYkKymrscA9YGAaEvqILt3dTsI004CT4CF5uLWmtBfGwGxwRL3hiDlipVKUCnlmJ1QGhBgQZWOMnBz2S/1k8Ey8Jzpy+MUoiJn3BaZF5yC8pkTmYBS2mCOnmyfZ5jIgNV1A+OhpyJOwlVwdNnaRPgK793RR2Nj+FT/0OukcK1v9OUtBKNojbO3HDKsoM9kAzbDoVuDA+WPbPZFLmZ+Gu5YEosW2b5Vvf5qCjFzxQgu12Be5sw+ogh+GXWEMs6CqiyKevqZhjVDfMkx28DY43e/rnHR1c7CWAPJ7NQv48CLujhkTEtq0zM64n7Rt8wdM8w9Z+17U2SSZ5mmlfMf3ntm3/9Y=
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
